module.exports = [{
  // uuid:1,
  content: `从我记事开始
  我就喜欢看星空
  而这并不是为了遇见外星人
  而是为了遇见你`,
  cntComment: 0,
  cntLike: 1,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: '原创',
  creator: {
    _id: "5ea3efe24a04761b842ff536",
    username: '苏长情',
    // intro: '愿有岁月可回首，且以深情共白头。',
    avatar: '/images/default.jpg'
  },
  comment: []
}, {
  // uuid:1,
  content: `我把春天当成一杯沁人心脾的茶，一饮而尽，肚里翻滚着整个春天，口呼娇媚芳香的气息。`,
  cntComment: 0,
  cntLike: 1,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['原创'],
  comment: []
}, {
  // uuid:1,
  content: '我认为世间最美的情话莫过于：当我说“我爱你”时，你便回答“我也是”。',
  cntComment: 0,
  cntLike: 0,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['原创'],
  comment: []
}, {
  // uuid:1,
  content: '维系我们之间关系的，不过是各取所需。',
  cntComment: 0,
  cntLike: 0,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['原创'],
  comment: []
}, {
  // uuid:1,
  content: `哪有什么地老天荒
  最后可以知道的
  是
  我们会
  骸骨实烂`,
  cntComment: 0,
  cntLike: 0,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['原创'],
  comment: []
}, {
  // uuid:1,
  content: `我把春天当成一杯沁人心脾的茶，一饮而尽，肚里翻滚着整个春天，口呼娇媚芳香的气息。`,
  cntComment: 0,
  cntLike: 1,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['原创'],
  comment: []
}, {
  // uuid:1,
  content: '我认为世间最美的情话莫过于：当我说“我爱你”时，你便回答“我也是”。',
  cntComment: 0,
  cntLike: 0,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['原创'],
  comment: []
}, {
  // uuid:1,
  content: '维系我们之间关系的，不过是各取所需。',
  cntComment: 0,
  cntLike: 0,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['原创'],
  comment: []
}, {
  // uuid:1,
  content: `哪有什么地老天荒
  最后可以知道的
  是
  我们会
  骸骨实烂`,
  cntComment: 0,
  cntLike: 0,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['原创'],
  comment: []
}, {
  // uuid:1,
  content: '物以稀为贵，我们在世上最觉稀少、最嫌不够的东西便是这迟早要结束的生命。',
  cntComment: 0,
  cntLike: 30,
  referAuthorName: '周国平',
  referWorkId: '',
  referWorkName: '《周国平散文精选》',
  tags: ['精选'],
  comment: []
}, {
  // uuid:1,
  content: '人心之不同如其面，要脚踏实地，不可舍己耘人。',
  cntComment: 0,
  cntLike: 30,
  referAuthorName: ' 林语堂',
  referWorkId: '',
  referWorkName: '《林语堂散文精选》',
  tags: ['精选'],
  comment: []
}, {
  // uuid:1,
  content: '物以稀为贵，我们在世上最觉稀少、最嫌不够的东西便是这迟早要结束的生命。',
  cntComment: 0,
  cntLike: 30,
  referAuthorName: '周国平',
  referWorkId: '',
  referWorkName: '《周国平散文精选》',
  tags: ['精选'],
  comment: []
}, {
  // uuid:1,
  content: '人心之不同如其面，要脚踏实地，不可舍己耘人。',
  cntComment: 0,
  cntLike: 30,
  referAuthorName: ' 林语堂',
  referWorkId: '',
  referWorkName: '《林语堂散文精选》',
  tags: ['精选'],
  comment: []
}, {
  // uuid:1,
  content: '物以稀为贵，我们在世上最觉稀少、最嫌不够的东西便是这迟早要结束的生命。',
  cntComment: 0,
  cntLike: 30,
  referAuthorName: '周国平',
  referWorkId: '',
  referWorkName: '《周国平散文精选》',
  tags: ['精选'],
  comment: []
}, {
  // uuid:1,
  content: '人心之不同如其面，要脚踏实地，不可舍己耘人。',
  cntComment: 0,
  cntLike: 30,
  referAuthorName: ' 林语堂',
  referWorkId: '',
  referWorkName: '《林语堂散文精选》',
  tags: ['精选'],
  comment: []
}, {
  // uuid:1,
  content: '物以稀为贵，我们在世上最觉稀少、最嫌不够的东西便是这迟早要结束的生命。',
  cntComment: 0,
  cntLike: 30,
  referAuthorName: '周国平',
  referWorkId: '',
  referWorkName: '《周国平散文精选》',
  tags: ['精选'],
  comment: []
}, {
  // uuid:1,
  content: '人心之不同如其面，要脚踏实地，不可舍己耘人。',
  cntComment: 0,
  cntLike: 30,
  referAuthorName: ' 林语堂',
  referWorkId: '',
  referWorkName: '《林语堂散文精选》',
  tags: ['精选'],
  comment: []
}, {
  // uuid:1,
  content: '物以稀为贵，我们在世上最觉稀少、最嫌不够的东西便是这迟早要结束的生命。',
  cntComment: 0,
  cntLike: 30,
  referAuthorName: '周国平',
  referWorkId: '',
  referWorkName: '《周国平散文精选》',
  tags: ['精选'],
  comment: []
}, {
  // uuid:1,
  content: '人心之不同如其面，要脚踏实地，不可舍己耘人。',
  cntComment: 0,
  cntLike: 30,
  referAuthorName: ' 林语堂',
  referWorkId: '',
  referWorkName: '《林语堂散文精选》',
  tags: ['精选'],
  comment: []
}, {
  // uuid:1,
  content: '物以稀为贵，我们在世上最觉稀少、最嫌不够的东西便是这迟早要结束的生命。',
  cntComment: 0,
  cntLike: 30,
  referAuthorName: '周国平',
  referWorkId: '',
  referWorkName: '《周国平散文精选》',
  tags: ['精选'],
  comment: []
}, {
  // uuid:1,
  content: '人心之不同如其面，要脚踏实地，不可舍己耘人。',
  cntComment: 0,
  cntLike: 30,
  referAuthorName: ' 林语堂',
  referWorkId: '',
  referWorkName: '《林语堂散文精选》',
  tags: ['精选'],
  comment: []
}, {
  // uuid:1,
  content: '物以稀为贵，我们在世上最觉稀少、最嫌不够的东西便是这迟早要结束的生命。',
  cntComment: 0,
  cntLike: 30,
  referAuthorName: '周国平',
  referWorkId: '',
  referWorkName: '《周国平散文精选》',
  tags: ['精选'],
  comment: []
}, {
  // uuid:1,
  content: '人心之不同如其面，要脚踏实地，不可舍己耘人。',
  cntComment: 0,
  cntLike: 30,
  referAuthorName: ' 林语堂',
  referWorkId: '',
  referWorkName: '《林语堂散文精选》',
  tags: ['精选'],
  comment: []
}, {
  // uuid:1,
  content: '我是预言家，昨晚查验了你的身份，你是，我儿子。',
  cntComment: 0,
  cntLike: 3,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['搞笑'],
  comment: []
}, {
  // uuid:1,
  content: '如果当年高考写作文要是有现在的文案水平，早就被清华北大录取了。',
  cntComment: 0,
  cntLike: 2,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['搞笑'],
  comment: []
}, {
  // uuid:1,
  content: '我是预言家，昨晚查验了你的身份，你是，我儿子。',
  cntComment: 0,
  cntLike: 3,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['搞笑'],
  comment: []
}, {
  // uuid:1,
  content: '如果当年高考写作文要是有现在的文案水平，早就被清华北大录取了。',
  cntComment: 0,
  cntLike: 2,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['搞笑'],
  comment: []
}, {
  // uuid:1,
  content: '我是预言家，昨晚查验了你的身份，你是，我儿子。',
  cntComment: 0,
  cntLike: 3,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['搞笑'],
  comment: []
}, {
  // uuid:1,
  content: '如果当年高考写作文要是有现在的文案水平，早就被清华北大录取了。',
  cntComment: 0,
  cntLike: 2,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['搞笑'],
  comment: []
}, {
  // uuid:1,
  content: '我是预言家，昨晚查验了你的身份，你是，我儿子。',
  cntComment: 0,
  cntLike: 3,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['搞笑'],
  comment: []
}, {
  // uuid:1,
  content: '如果当年高考写作文要是有现在的文案水平，早就被清华北大录取了。',
  cntComment: 0,
  cntLike: 2,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['搞笑'],
  comment: []
}, {
  // uuid:1,
  content: '我是预言家，昨晚查验了你的身份，你是，我儿子。',
  cntComment: 0,
  cntLike: 3,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['搞笑'],
  comment: []
}, {
  // uuid:1,
  content: '如果当年高考写作文要是有现在的文案水平，早就被清华北大录取了。',
  cntComment: 0,
  cntLike: 2,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['搞笑'],
  comment: []
}, {
  // uuid:1,
  content: '客户虐我千百遍，我待客户如初恋。房东骂我心不堵，我当自己是保姆。',
  cntComment: 0,
  cntLike: 0,
  referAuthorName: '六六',
  referWorkId: '',
  referWorkName: '《安家》',
  tags: ['语录'],
  comment: []
}, {
  // uuid:1,
  content: `我喜欢吃泡
  和我愿意陪你吃泡面
  和我只配和你吃泡面
  和你只给我吃泡面
  是完全不同的概念好吗？`,
  cntComment: 0,
  cntLike: 0,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['语录'],
  comment: []
}, {
  // uuid:1,
  content: '很多时候都是自己挖了个坑,然后义无反顾的跳进去,坑是自己控的,跳也是自己跳的,最后爬不出来的也是自己。',
  cntComment: 0,
  cntLike: 5,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['生活'],
  comment: []
}, {
  // uuid:1,
  content: '如今一个人听歌事们是在好把军觉得难过',
  cntComment: 0,
  cntLike: 5,
  referAuthorName: '许嵩',
  referWorkId: '',
  referWorkName: '《全球这外冷》',
  tags: ['歌词'],
  comment: []
}, {
  // uuid:1,
  content: `丹丹，这次机会对我来说真的很重要。
  雪伦，你对我来说很重要。`,
  cntComment: 0,
  cntLike: 5,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '《亲家过年》',
  tags: ['电影'],
  comment: []
}, {
  // uuid:1,
  content: 'love is a touch yet not a touch',
  cntComment: 0,
  cntLike: 1,
  referAuthorName: '塞格林',
  referWorkId: '',
  referWorkName: '《破碎故事之心》',
  tags: ['英语'],
  comment: []
}, {
  // uuid:1,
  content: '答应过你的我都记得，可是你却忘了还有那么个我的存在。',
  cntComment: 0,
  cntLike: 5,
  referAuthorName: '',
  referWorkId: '',
  referWorkName: '',
  tags: ['随笔'],
  comment: []
}, {
  // uuid:1,
  content: '大儿锄豆溪东，中儿正织鸡笼。',
  cntComment: 0,
  cntLike: 5,
  referAuthorName: '辛弃疾',
  referWorkId: '',
  referWorkName: '《清平乐·村居》',
  tags: ['诗词'],
  comment: []
}]